# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS=" "
     - R_CHECK_ARGS="--as-cran"
     - BOOTSTRAP_LATEX="1"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - cd R-package
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - cat /home/travis/build/gtesei/fast-furious/R-package/fastfurious.Rcheck/00check.log

install:
  - ./travis-tool.sh install_deps
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get -qq update
  - ./travis-tool.sh github_package jimhester/covr@4cae287abde5e2cf0c3c73aedeaec4d902dfd3ed
  - ./travis-tool.sh github_package jimhester/lintr@21607f469c2ce4f999d04a836f9348038a7282e2
  - ./travis-tool.sh github_package hadley/devtools@52bc15bb7eb87105bbf799d7f784054921146c02
  - ./travis-tool.sh github_package hadley/testthat@c67018fa4970ee3390ea2056efe56726626b07e3

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


