# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c
sudo: required

env:
   global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
   matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

before_install:
  - cd R-package
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo mkdir -p /usr/lib/R/library
  - echo 'R_LIBS=/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
  - sudo chmod 2777 /usr/lib/R/library
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install car
  - ./travis-tool.sh r_binary_install reshape2
  - ./travis-tool.sh r_binary_install foreach
  - ./travis-tool.sh r_binary_install plyr
  - ./travis-tool.sh r_binary_install nlme
  - ./travis-tool.sh r_binary_install BradleyTerry2
  - ./travis-tool.sh r_binary_install e1071
  - ./travis-tool.sh r_binary_install earth
  - ./travis-tool.sh r_binary_install fastICA
  - ./travis-tool.sh r_binary_install gam
  - ./travis-tool.sh r_binary_install ipred
  - ./travis-tool.sh r_binary_install kernlab
  - ./travis-tool.sh r_binary_install klaR
  - ./travis-tool.sh r_binary_install MASS
  - ./travis-tool.sh r_binary_install ellipse
  - ./travis-tool.sh r_binary_install mda
  - ./travis-tool.sh r_binary_install mgcv
  - ./travis-tool.sh r_binary_install mlbench
  - ./travis-tool.sh r_binary_install nnet
  - ./travis-tool.sh r_binary_install party
  - ./travis-tool.sh r_binary_install pls
  - ./travis-tool.sh r_binary_install pROC
  - ./travis-tool.sh r_binary_install proxy
  - ./travis-tool.sh r_binary_install randomForest
  - ./travis-tool.sh r_binary_install RANN
  - ./travis-tool.sh r_binary_install spls
  - ./travis-tool.sh r_binary_install subselect
  - ./travis-tool.sh r_binary_install pamr
  - ./travis-tool.sh r_binary_install superpc
  - ./travis-tool.sh r_binary_install Cubist
  - ./travis-tool.sh r_binary_install testthat
  - ./travis-tool.sh r_binary_install rARPACK
  - ./travis-tool.sh r_binary_install ggplot2
  - ./travis-tool.sh r_binary_install reshape2
  - ./travis-tool.sh r_binary_install data.table
  - ./travis-tool.sh install_github jimhester/covr
  - ./travis-tool.sh install_github terrytangyuan/lfda

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r ROSE DMwR

script: 
  - ./travis-tool.sh run_tests
  - cat /home/travis/build/gtesei/fast-furious/R-package/fastfurious.Rcheck/00check.log
  - cat /home/travis/build/gtesei/fast-furious/R-package/fastfurious.Rcheck/00install.out
  - cat /home/travis/build/gtesei/fast-furious/R-package/fastfurious.Rcheck/tests/testthat.Rout

after_failure:
  - ./travis-tool.sh dump_logs
  - cat /home/travis/build/gtesei/fast-furious/R-package/fastfurious.Rcheck/tests/testthat.Rout

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


