Walmart Recruiting Store Sales Forecasting
========================================================

Content 
-------------------------
1. **Generating a feature set (file) for each dept and store**
2. **Fitting with a liner regressor and see submitted results**
3. **Fitting sales time series and see submitted results**

.

1. Generating a feature set (file) for each dept and store
-------------------------

see walmart1.Rmd 

2. Fitting with a liner regressor and see submitted results 
-------------------------

```{r,warning=F} 

##### utils  
library(leaps)
library(glmnet)
library (pls)
library (splines)

predict.regsubsets =function (reg , formula , newdata ,id ,...){
  #form=as.formula(reg$call [[2]])
  form = as.formula(formula)
  mat=model.matrix(form,newdata)
  coefi=coef(reg ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi 
}

getWMAE = function(pred, data  ) {
    ares = abs(pred - data$Weekly_Sales)
    l = dim(data)[1] 
    w = 1 * (!data$IsHoliday) + 5 * data$IsHoliday
    wmae = sum(ares * w) / (sum(w))
}

# returns string w/o leading or trailing whitespace
trim = function (x) gsub("^\\s+|\\s+$", "", x)

# build id as concatenation of Store and Dept 
buildId = function(x) {  
  prefix = paste(trim(as.character(x[1])),'_',sep='') 
  id = paste(prefix,trim(as.character(x[2])),sep='')
}

### load files 
#base.path = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/walmart-recruiting-store-sales-forecasting/"

base.path = "C:/docs/ff/gitHub/fast-furious/dataset/walmart-recruiting-store-sales-forecasting/"


train.fn = paste(base.path,"train.zat",sep="")
test.fn = paste(base.path,"test.zat",sep="")
sampleSubmission.fn = paste(base.path,"sampleSubmission.zat",sep="")
features.fn = paste(base.path,"features.zat",sep="")
stores.fn = paste(base.path,"stores.zat",sep="")

#train.csv = read.csv(train.fn)
test.csv = read.csv(test.fn)
#sampleSubmission.csv = read.csv(sampleSubmission.fn)
#features.csv = read.csv(features.fn)
#stores.csv = read.csv(stores.fn)

##
#train.csv$Date = as.character(train.csv$Date)
test.csv$Date = as.character(test.csv$Date)
#features.csv$Date = as.character(features.csv$Date)

test.csv$id = apply(test.csv,1, buildId)
#train.csv$id = apply(train.csv,1, buildId)

head(test.csv)
tail(test.csv)
ids = unique(test.csv$id)
ids.num = length(ids)

ids.num

```

Processing each id 

```{r,warning=F} 

selectModel = function (traindata , form="Weekly_Sales ~ .") {
  # k-fold
  var.feat = length(names(traindata)) - 1
  k=4
  #set.seed(1)
  folds=sample(1:k,nrow(traindata),replace=TRUE)
  cv.errors=matrix(NA,k,var.feat, dimnames=list(NULL, paste(1:var.feat)))
  cv.mae=matrix(NA,k,var.feat, dimnames=list(NULL, paste(1:var.feat)))
  cv.wmae=matrix(NA,k,var.feat, dimnames=list(NULL, paste(1:var.feat)))
  
  for(j in 1:k) {
    best.fit = regsubsets( Weekly_Sales ~ . , data = traindata[folds!=j,], nvmax = var.feat)
    #print(summary(best.fit))
    for (i in (1:var.feat) ) {
      pred = predict(best.fit , form, traindata[folds==j,] , id = i)
      cv.errors[j,i] = mean((traindata$Weekly_Sales[folds==j]-pred)^2)
      cv.mae[j,i] = mean(abs((traindata$Weekly_Sales[folds==j]-pred)))
      cv.wmae[j,i] = getWMAE(pred , traindata[folds==j , ] )
      #print(cv.wmae[j,i])
      } 
    }
  
  ## WMAE
  mean.cv.wmae=apply(cv.wmae ,2,mean)
  print(mean.cv.wmae)
  print("min WMAE:")
  print(min(mean.cv.wmae))
  m = which.min(mean.cv.wmae)
  print(as.numeric(m))
  #par(mfrow=c(1,1))
  plot(mean.cv.wmae ,type="b")
  
  ##
  train=sample(c(TRUE,FALSE), nrow(traindata),rep=TRUE)
  test =(!train)
  tl = length(traindata[test,1])
  best.fit = regsubsets( Weekly_Sales ~ . , data = traindata[train,], nvmax = var.feat)
  pred = predict(best.fit , "Weekly_Sales ~ .", traindata[test,] , id = m)
  plot( x=c((1:tl),(1:tl)) ,  y=c(traindata[ test , 1] , pred) , col=1:2 , lty=1:2 )
  legend("topleft", c("weekly sales", "Reg" ) , lty = 1:2, col = 1:2)
  hist(  (traindata[ test , 1] - pred) )
  plot( pred , (traindata[ test , 1] - pred)^2 )
  
  
}

miss.id.train = NULL

c = 0
for (id in ids) {
  print("processing id:")
  print(id)
  fn.tr = paste(paste(paste(base.path,"gen/",sep=''),id,sep=''),'_train.zat',sep='')
  fn.ts = paste(paste(paste(base.path,"gen/",sep=''),id,sep=''),'_test.zat',sep='')
  
  if (! file.exists(fn.tr) ){
    print(paste("no train set present for id ",id,sep=''))
    if (is.null(miss.id.train)) 
      miss.id.train = c(id)
    else 
      miss.id.train = c(miss.id.train,id)
  } 
  
  train.csv = read.csv(fn.tr)
  test.csv = read.csv(fn.tr)
  
  print(head(train.csv))
  
  #######
  train.data.full = data.frame(Weekly_Sales = train.csv$Weekly_Sales  , 
                               Temperature = train.csv$Temperature, Fuel_Price = train.csv$Fuel_Price ,
                               CPI = train.csv$CPI , Unemployment = train.csv$Unemployment , 
                               IsHoliday = train.csv$IsHoliday.y , MarkDown1 = train.csv$MarkDown1 , 
                               MarkDown2 = train.csv$MarkDown2 , 
                               MarkDown3 = train.csv$MarkDown3 , MarkDown4 = train.csv$MarkDown4 ,
                               MarkDown5 = train.csv$MarkDown5 )

  train.data.red = data.frame(Weekly_Sales = train.csv$Weekly_Sales  , 
                              Temperature = train.csv$Temperature, Fuel_Price = train.csv$Fuel_Price , 
                              CPI = train.csv$CPI , Unemployment = train.csv$Unemployment , 
                              IsHoliday = train.csv$IsHoliday.y )
  
  
  train.data.full = na.omit(train.data.full)
  train.data.red = na.omit(train.data.red)
  
  ##### Model Selection 
  selectModel(train.data.full)
  selectModel(train.data.red)
  
  ##### Ridge Regression 
  train.data = train.data.full
  var.feat = length(names(train.data)) - 1
  
  x=model.matrix(Weekly_Sales~.,train.data)[,-1]
  y=train.data$Weekly_Sales
  grid=10^seq(10,-2,length=100)
  ridge.mod=glmnet(x,y,alpha=0,lambda=grid)
  
  #set.seed(1)
  train = sample(1:nrow(x), nrow(x)/2)
  test = (-train) 
  y.test=y[test]
  cv.out=cv.glmnet(x[train ,],y[train],alpha=0 , nfolds=10)
  plot(cv.out)
  bestlam=cv.out$lambda.min
  print("bestlam:")
  print(bestlam)
  ridge.pred=predict(cv.out,s=bestlam ,newx=x[test,])
  #mean((ridge.pred-y.test)^2)
  print("MAE:")
  print(mean(abs(ridge.pred-y.test)))
  predict(ridge.mod, s = bestlam, type = "coefficients")[1:(var.feat + 1), ]
  
  ##### PCA Regression 
  train = cbind(rep(TRUE,floor(length(train.data.red)/2)), rep(FALSE,length(train.data.red) - floor(length(train.data.red)/2) ))
  test = (! train)
  pcr.fit=pcr(Weekly_Sales~., data=train.data.red[train,]  ,scale =TRUE , validation ="CV")
  validationplot(pcr.fit ,val.type="MSEP")
  pcr.pred=predict (pcr.fit ,newdata=train.data.red[test ,], ncomp =4)
  print(mean(abs(pcr.pred -y[test])))
  
  ##### Splines
  print("Splines ... ")
  fform = "Weekly_Sales ~ .+ ns(Temperature) + ns(Fuel_Price) + ns(CPI)  + ns(Unemployment)  "
  selectModel(train.data.red , form=fform)
 
  
  
  
  c = c + 1
  if (c > 10) break 
}

miss.id.train 

```
