Troubleshooting
========================================================

Content 
-------------------------
1. **Generating a feature set (file) for each dept and store**
2. **Fitting with a liner regressor and see submitted results**
3. **Fitting sales time series and see submitted results**

.

1. Generating a feature set (file) for each dept and store
-------------------------

see walmart1.Rmd 

2. Fitting with several regressors and choosing best performers  
-------------------------

see walmart4.Rmd 


2.1 Predicting on test set and build submission file  
-------------------------


```{r,warning=F} 
##### utils  
library(leaps)
library(glmnet)
library (pls)
library (splines)
library (randomForest)
library (gbm)

# returns string w/o leading or trailing whitespace
trim = function (x) gsub("^\\s+|\\s+$", "", x)

predict.regsubsets =function (reg , formula , newdata ,id ,...){
  #form=as.formula(reg$call [[2]])
  form = as.formula(formula)
  mat=model.matrix(form,newdata)
  coefi=coef(reg ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi 
}

## compute difference between 2 data.frame 
fun.12 <- function(x.1,x.2,...){
  x.1p <- do.call("paste", x.1)
  x.2p <- do.call("paste", x.2)
  x.1[! x.1p %in% x.2p, ]
}

kfolds = function(k,data.length) {
  k = min(k,data.length)
  folds = rep(NA,data.length)
  labels = 1:data.length
  st = floor(data.length/k)
  al_labels = NULL
  for (s in 1:k) {
    x = NULL
    if (is.null(al_labels))
      x = sample(labels,st)
    else
      x = sample(labels[-al_labels],st)
    
    folds[x] = s
    if (is.null(al_labels))
      al_labels = x
    else
      al_labels = c(al_labels,x)
    }
  ss = 1
  for (s in 1:length(folds)){
    if (is.na(folds[s])) {
      folds[s] = ss
      ss = ss + 1
      } 
    }
  folds
}

getWMAE = function(pred, data  ) {
    ares = abs(pred - data$Weekly_Sales)
    l = dim(data)[1] 
    w = 1 * (!data$IsHoliday) + 5 * data$IsHoliday
    wmae = sum(ares * w) / (sum(w))
}

# build id as concatenation of Store, Dept and Date 
buildDeepId = function(x) {  
  prefix1 = paste(trim(as.character(x[1])),'_',sep='')
  prefix2 = paste(prefix1,trim(as.character(x[2])),sep='')
  prefix3 = paste(prefix2,'_',sep='')
  id = paste(prefix3,trim(as.character(x[3])),sep='')
}

# build id as concatenation of Store and Dept 
buildId = function(x) {  
  prefix = paste(trim(as.character(x[1])),'_',sep='') 
  id = paste(prefix,trim(as.character(x[2])),sep='')
}

```

```{r,warning=F} 
#base.path = "C:/docs/ff/gitHub/fast-furious/dataset/walmart-recruiting-store-sales-forecasting/"
base.path = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/walmart-recruiting-store-sales-forecasting/"
#base.path = "C:/____PERSONAL____/data_analytics/fast-furious/fast-furious/dataset/walmart-recruiting-store-sales-forecasting/"

test.all.fn = paste(base.path,"test.zat",sep="")
sampleSubmission.fn = paste(base.path,"sampleSubmission.zat",sep="")

test.all.csv = read.csv(test.all.fn)
sampleSubmission.csv = read.csv(sampleSubmission.fn)

##
test.all.csv$Date = as.character(test.all.csv$Date)
test.all.csv$id = apply(test.all.csv,1, buildId)
test.all.csv$deepid = apply(test.all.csv,1, buildDeepId)
test.all.csv$pred = NA

ids = unique(test.all.csv$id)
ids.num = length(ids)
```


```{r,warning=F} 

perror = NULL
perf = data.frame(id = ids , wmae = rep(NA,ids.num) , mae = rep(NA,ids.num), 
                  errors = rep(NA,ids.num) , test_size = rep(NA,ids.num))

predictOnTestSet = function (cname,pwin,par1,id,train.data,test.data,doPlot = T) {
  
  pred.mean = NULL
  
  k=10
  folds = kfolds(k,nrow(train.data)) 
  
  cv.errors=matrix(NA,k,1, dimnames=list(NULL, paste(1:1)))
  cv.mae=matrix(NA,k,1, dimnames=list(NULL, paste(1:1)))
  cv.wmae=matrix(NA,k,1, dimnames=list(NULL, paste(1:1)))
  preds =matrix(NA,k,dim(test.data)[1], dimnames=list(NULL, paste(1:dim(test.data)[1])))
  
  for(j in 1:k) {  
    
    pred = NULL
    pred.xval = NULL
    
    traindata = train.data[folds != j,]
    xvaldata = train.data[folds == j,]
    testdata = test.data 
    
    tryCatch({
      if (pwin == 1) { ## (forward) stepwise selection
        form="Weekly_Sales ~ ."
        var.feat = length(names(traindata)) - 1
        best.fit = regsubsets( Weekly_Sales ~ . , data = traindata, nvmax = var.feat)
        pred = predict(best.fit , as.formula(form), testdata, id = par1)
        pred.xval = predict(best.fit , as.formula(form), xvaldata, id = par1)
        
        } else if (pwin == 2) { ## (forward) stepwise selection + splines  
          form="Weekly_Sales ~ ."
          var.feat = length(names(traindata)) - 1
          best.fit = regsubsets( Weekly_Sales ~ . , data = traindata, nvmax = var.feat)
          #pred = predict(best.fit , form, traindata, id = par1)
          
          mod.prd = predict(best.fit , as.formula(form),newdata=traindata, id = par1) 
          mod.prd.test = predict(best.fit , as.formula(form),newdata=testdata , id = par1) 
          mod.prd.xval = predict(best.fit , as.formula(form),newdata=xvaldata , id = par1) 
          
          spl.fit = smooth.spline(x=mod.prd,y=traindata$Weekly_Sales,cv=TRUE )
          pred = predict(spl.fit , mod.prd.test   )$y 
          pred.xval = predict(spl.fit , mod.prd.xval   )$y 
          
        } else if (pwin == 3) { ##ridge regression  
          x=model.matrix(Weekly_Sales~.,traindata)[,-1]
          y=traindata$Weekly_Sales
          grid=10^seq(10,-2,length=100)
          cv.out=cv.glmnet(x,y,alpha=0 , nfolds=10)
          bestlam=cv.out$lambda.min
          
          x.test=model.matrix(Weekly_Sales~.,testdata)[,-1]
          x.xval=model.matrix(Weekly_Sales~.,xvaldata)[,-1]
          pred=predict(cv.out,s=bestlam ,newx=x.test)
          pred.xval=predict(cv.out,s=bestlam ,newx=x.xval)
            
        } else if (pwin == 4) { ##ridge regression   + splines   
          x=model.matrix(Weekly_Sales~.,traindata)[,-1]
          y=traindata$Weekly_Sales
          grid=10^seq(10,-2,length=100)
          cv.out=cv.glmnet(x,y,alpha=0 , nfolds=10)
          bestlam=cv.out$lambda.min
          x.test=model.matrix(Weekly_Sales~.,testdata)[,-1]
          x.xval = model.matrix(Weekly_Sales~.,xvaldata)[,-1]
          #pred=predict(cv.out,s=bestlam ,newx=x.test)
              
          mod.prd = predict(cv.out,s=bestlam ,newx=x)
          mod.prd.test = predict(cv.out,s=bestlam ,newx=x.test)
          mod.prd.xval = predict(cv.out,s=bestlam ,newx=x.xval)
          spl.fit = smooth.spline(x=mod.prd,y=traindata$Weekly_Sales,cv=TRUE)
          pred = predict(spl.fit , mod.prd.test   )$y
          pred.xval = predict(spl.fit , mod.prd.xval   )$y
              
        } else if (pwin == 5) { ## lasso reegression
          stop("predictor (lasso,5) not supported")
                
        } else if (pwin == 6) { ## lasso reegression  + splines   
          stop("predictor (lasso+splines,6) not supported")
                  
        } else if (pwin == 7) { ## splines 
          fform = "Weekly_Sales ~ .+ ns(Temperature) + ns(Fuel_Price) + ns(CPI)  + ns(Unemployment) "
          var.feat = length(names(traindata)) - 1
          best.fit = regsubsets( as.formula(fform) , data = traindata, nvmax = var.feat)
          pred = predict(best.fit , as.formula(fform), testdata , id = par1)
          pred.xval = predict(best.fit , as.formula(fform), xvaldata , id = par1)
                    
        } else if (pwin == 8) { ## pca  
          stop("predictor (pca,8) not supported")
                      
        } else if (pwin == 9) { ## pca + splines  
          stop("predictor (pca+splines,9) not supported")
                        
        } else if (pwin == 10) { ## random forest  
          rf =randomForest(Weekly_Sales~. ,data=traindata, importance =TRUE)
          pred = predict (rf ,newdata = testdata)
          pred.xval = predict (rf ,newdata = xvaldata)
                          
        } else if (pwin == 11) { ## random forest + splines 
          rf =randomForest(Weekly_Sales~. ,data=traindata, importance =TRUE)
          mod.prd = predict (rf ,newdata = traindata)
          mod.prd.test = predict (rf ,newdata = testdata)
          mod.prd.xval = predict (rf ,newdata = xvaldata)
          spl.fit = smooth.spline(x=mod.prd,y=traindata$Weekly_Sales,cv=TRUE)
          pred = predict(spl.fit , mod.prd.test   )$y
          pred.xval = predict(spl.fit , mod.prd.xval   )$y
                            
        } else if (pwin == 12) { ## Boosting  
          stop("predictor (boosting,12) never won")
                              
        } else if (pwin == 13) { ## Boosting + splines 
          stop("predictor (boosting+splines,13) never won")
                                
        } else if (pwin == 14) { ## Mean 
          pred = rep(mean(traindata$Weekly_Sales),dim(testdata)[1])
          pred.xval = rep(mean(traindata$Weekly_Sales),dim(xvaldata)[1])
                                  
        } else {
          stop ("bad predictor selector")
        }
      }, error = function(e) {  })
    
      ######### 
      if (is.null(pred))  {
        pred = rep(mean(traindata$Weekly_Sales),dim(testdata)[1])
        pred.xval = rep(mean(traindata$Weekly_Sales),dim(xvaldata)[1])
        perror <<- c(perror,pwin)
      }
    
      cv.errors[j,1] = mean((xvaldata$Weekly_Sales-pred.xval)^2)
      cv.mae[j,1] = mean(abs((xvaldata$Weekly_Sales-pred.xval)))
      cv.wmae[j,1] = getWMAE(pred.xval , xvaldata )  
    
#       for (i in (1:dim(test.data)[1]) ) 
#         preds[j,i] = pred[i] 
      preds[j,1:(dim(test.data)[1])] = pred
  }
  
  ### pred.mean 
  mean.cv.mae=apply(cv.mae ,2,mean)

  mean.cv.wmae=apply(cv.wmae ,2,mean)  
#   print(id)
#   print(mean.cv.wmae)
#   print(cv.wmae) 

  mean.cv.errors=apply(cv.errors ,2,mean)
  pred.mean = apply(preds ,2,mean)
  
  perf$mae[perf$id == id] <<- mean.cv.mae
  perf$wmae[perf$id == id] <<- mean.cv.wmae
  perf$errors[perf$id == id] <<- mean.cv.errors
  perf$test_size[perf$id == id] <<- dim(test.data)[1]
  
  tryCatch({
    if (doPlot) {
          ts_train = ts(as.vector(train.data$Weekly_Sales), start = c(2010, 2) , frequency=52 )
          ts_test = ts(pred.mean, start = end(ts_train) , frequency = frequency(ts_train))
          ts.plot(ts_train, ts_test, col = 1:2, lty = 1:2)
          legend("topleft", c(cname, "pred_on_testset"), lty = 1:2, col = 1:2)
    }
  }, error = function(e) {})
  
  pred.mean
}

```



Deserializing **MP.min** and **MP.min.all** ... 

```{r,warning=F} 
MP.min.fn = paste(paste(base.path,"gen/",sep=''),"MP_min_comp.zat",sep='')
MP.min = read.csv(MP.min.fn)
head(MP.min)
tail(MP.min)
 
MP.min.all.fn = paste(paste(base.path,"gen/",sep=''),"MP_min_all_comp.zat",sep='')
MP.min.all = read.csv(MP.min.all.fn)

head(MP.min.all)
tail(MP.min.all)
```


```{r,warning=F} 
sum(is.na(test.all.csv$pred))
sum(is.na(test.all.csv$pred)) / dim(test.all.csv)[1]

c = 1
MAX = 700000
do_plot = F

ptm <- proc.time()

for (id in ids) {
  pred = NULL 
  
  
  test.csv.fn = paste(paste(paste(base.path,"gen/",sep=''),id,sep=''),'_test.zat',sep='')
  test.csv = read.csv(test.csv.fn)
  test.csv$pred = NA
  test.csv$Weekly_Sales = 0
  test.csv$deepid = apply(test.csv,1, buildDeepId)
  
  
  ## handling cases with no train set 
  mp = MP.min[MP.min$Active == 1 & MP.min$ID_St_Dept == id , ]
  mp.all = MP.min.all[MP.min.all$Active == 1 & MP.min.all$ID_St_Dept == id , ]
  
  if (mp$P_WIN == 15) {
    pred = rep(mp$PAR1,dim(test.csv)[1])
    test.csv$pred[test.csv$id == id] = pred 
    test.all.csv$pred[test.all.csv$id == id] = pred
    
    next 
  } 
  
  
  ############# load train and test files 
  train.csv.fn = paste(paste(paste(base.path,"gen/",sep=''),id,sep=''),'_train.zat',sep='')
  train.csv = read.csv(train.csv.fn)
  
  ## train
  train.data.full = data.frame(Weekly_Sales = train.csv$Weekly_Sales  , 
                               Temperature = train.csv$Temperature, Fuel_Price = train.csv$Fuel_Price ,
                               CPI = train.csv$CPI , Unemployment = train.csv$Unemployment , 
                               IsHoliday = train.csv$IsHoliday.y , MarkDown1 = train.csv$MarkDown1 , 
                               MarkDown2 = train.csv$MarkDown2 , 
                               MarkDown3 = train.csv$MarkDown3 , MarkDown4 = train.csv$MarkDown4 ,
                               MarkDown5 = train.csv$MarkDown5 )

  train.data.red = data.frame(Weekly_Sales = train.csv$Weekly_Sales  , 
                              Temperature = train.csv$Temperature, Fuel_Price = train.csv$Fuel_Price , 
                              CPI = train.csv$CPI , Unemployment = train.csv$Unemployment , 
                              IsHoliday = train.csv$IsHoliday.y )
  
  train.data.full = na.omit(train.data.full)   ### 1 
  train.data.red = na.omit(train.data.red)     ### 2 
  
  ## let's see best dataset
  if (mp$ID_DS == 2 | 1== 1) { ## best data set is the reduced one 
    cname = paste(id,"train",sep='_')
    cname = paste(cname,mp$P_WIN,sep='_p=')
    cname = paste(cname,mp$ID_DS,sep='_ds=')
    test.data.red = data.frame( Weekly_Sales = test.csv$Weekly_Sales  , 
                              Temperature = test.csv$Temperature, Fuel_Price = test.csv$Fuel_Price , 
                              CPI = test.csv$CPI , Unemployment = test.csv$Unemployment , 
                              IsHoliday = test.csv$IsHoliday.y)
    
    pred = predictOnTestSet (cname,mp.all$P_WIN[mp.all$ID_DS == 2],mp.all$PAR1[mp.all$ID_DS == 2],id,train.data.red,test.data.red,doPlot=do_plot)
    
  } else { ## best data set is the full one 
    test.data.full = data.frame( Weekly_Sales = test.csv$Weekly_Sales  , 
                               Temperature = test.csv$Temperature, Fuel_Price = test.csv$Fuel_Price ,
                               CPI = test.csv$CPI , Unemployment = test.csv$Unemployment , 
                               IsHoliday = test.csv$IsHoliday.y , MarkDown1 = test.csv$MarkDown1 , 
                               MarkDown2 = test.csv$MarkDown2 , 
                               MarkDown3 = test.csv$MarkDown3 , MarkDown4 = test.csv$MarkDown4 ,
                               MarkDown5 = test.csv$MarkDown5 )
    
    #############
#     cname = paste(id,"train",sep='_')
#     cname = paste(cname,mp.all$P_WIN[mp.all$ID_DS == 1],sep='_p=')
#     cname = paste(cname,mp.all$ID_DS[mp.all$ID_DS == 1],sep='_ds=')
#     pred = predictOnTestSet (cname, mp.all$P_WIN[mp.all$ID_DS == 1] , mp.all$PAR1[mp.all$ID_DS == 1], train.data.full, test.data.full, doPlot = do_plot)
    ############
  
    test.data.full$idx = rownames(test.data.full)
    dim0 = dim(test.data.full)[1]
    test.full = na.omit(test.data.full)
    test.na = fun.12(test.data.full,test.full)

    stopifnot(dim0 == dim(test.full)[1] + dim(test.na)[1])

    idx.full = test.full$idx
    idx.red = test.na$idx
    
    test.full.action = data.frame( Weekly_Sales = test.full$Weekly_Sales  , 
                               Temperature = test.full$Temperature, Fuel_Price = test.full$Fuel_Price ,
                               CPI = test.full$CPI , Unemployment = test.full$Unemployment , 
                               IsHoliday = test.full$IsHoliday , MarkDown1 = test.full$MarkDown1 , 
                               MarkDown2 = test.full$MarkDown2 , 
                               MarkDown3 = test.full$MarkDown3 , MarkDown4 = test.full$MarkDown4 ,
                               MarkDown5 = test.full$MarkDown5 )
    
    test.red.action = data.frame( Weekly_Sales = test.na$Weekly_Sales  , 
                              Temperature = test.na$Temperature, Fuel_Price = test.na$Fuel_Price , 
                              CPI = test.na$CPI , Unemployment = test.na$Unemployment , 
                              IsHoliday = test.na$IsHoliday)
    
    cname = paste(id,"test",sep='_')
    cname = paste(cname,mp.all$P_WIN[mp.all$ID_DS == 1],sep='_p=')
    cname = paste(cname,mp.all$ID_DS[mp.all$ID_DS == 1],sep='_ds=')
    pred.full = predictOnTestSet (cname, mp.all$P_WIN[mp.all$ID_DS == 1] , mp.all$PAR1[mp.all$ID_DS == 1], id, train.data.full, test.full.action , doPlot = do_plot)
    
    cname = paste(id,"test",sep='_')
    cname = paste(cname,mp.all$P_WIN[mp.all$ID_DS == 2],sep='_p=')
    cname = paste(cname,mp.all$ID_DS[mp.all$ID_DS == 2],sep='_ds=')
    pred.red = predictOnTestSet (cname,  mp.all$P_WIN[mp.all$ID_DS == 2] , mp.all$PAR1[mp.all$ID_DS == 2], id, train.data.red, test.red.action ,    doPlot = do_plot)
    
    pred.full.mrg = data.frame(idx=as.numeric(idx.full), preds = pred.full) 
    colnames(pred.full.mrg) = c("idx","preds")
    #pred.full.mrg$idx = as.numeric(pred.full.mrg$idx)
    pred.red.mrg = data.frame(idx=as.numeric(idx.red), preds = pred.red) 
    colnames(pred.red.mrg) = c("idx","preds")
    #pred.red.mrg$idx = as.numeric(pred.red.mrg$idx)
    
    pred.mrg = rbind(pred.full.mrg,pred.red.mrg)
    
    pred.mrg$idx = as.numeric(pred.mrg$idx)
    pred = pred.mrg$preds[with(pred.mrg, order(idx))]

    stopifnot(dim(pred) == dim(test.csv)[1])
  }
  
  test.csv$pred[test.csv$id == id] = pred 
  test.all.csv$pred[test.all.csv$id == id] = pred
   
  ## testing stuff 
  c = c + 1
  if (c > MAX) break 
}

```

Elapsed time in loop:
```{r,warning=F} 
tm = proc.time() - ptm
tm

err = data.frame(pred_id = 1:15,errors=rep(NA,15))
for (i in 1:15) {
  err$errors[err$pred_id == i] = sum(perror == i)
}
err

#perf[!is.na(perf$wmae),]
print(mean(perf$wmae[!is.na(perf$wmae)]))
```

Merging and storing predictions ... 
```{r,warning=F} 
sum(is.na(test.all.csv$pred))
sum(is.na(test.all.csv$pred)) / dim(test.all.csv)[1]

test.all.csv$deepid = as.character(test.all.csv$deepid)
sampleSubmission.csv$Id = as.character(sampleSubmission.csv$Id)
sub.merge = merge(sampleSubmission.csv,test.all.csv,by.x=c("Id"),by.y=c("deepid"),all.x=T,all.y=F)
sub = data.frame(Id = sub.merge$Id, Weekly_Sales = sub.merge$pred)

sub.fn = paste(base.path,"sub_main.zat",sep="")
write.csv(sub,quote=F,row.names=F,file=sub.fn)
```


3. Fitting sales time series and see submitted results 
-------------------------
