---
title: "11_Facets"
author: "Gino Tesei"
date: "December 14, 2015"
output: html_document
---

## 1. Splitting Data into Subplots with Facets
Use facet_grid() or facet_wrap(), and specify the variables on which to split.
```{r}
library(ggplot2)
library(gcookbook) # For the data set 

library(plyr)

# The base plot 
p <- ggplot( mpg, aes( x = displ, y = hwy)) + 
  geom_point()

# Faceted by drv, in vertically arranged subpanels 
p + facet_grid( drv ~ .) 

# Faceted by cyl, in horizontally arranged subpanels 
p + facet_grid(. ~ cyl) 

# Split by drv (vertical) and cyl (horizontal) 
p + facet_grid( drv ~ cyl)

# With facet_wrap(), the subplots are laid out horizontally and wrap around, like words on a page
# Facet on class 
# Note there is nothing before the tilde 
p + facet_wrap( ~ class)

# These will have the same result: 2 rows and 4 cols 
p + facet_wrap( ~ class, nrow = 2) 
p + facet_wrap( ~ class, ncol = 4)
```

## 2. Using Facets with Different Axes
```{r}
# The base plot 
p <- ggplot( mpg, aes( x = displ, y = hwy)) + 
  geom_point() 

# With free y scales 
p + 
  facet_grid( drv ~ cyl, scales ="free_y") 

# With free x and y scales 
p + 
  facet_grid( drv ~ cyl, scales ="free")
```

## 3. Changing the Text of Facet Labels
```{r}
# Make a copy of the original data 
mpg2 <- mpg 

# Rename 4 to 4wd, f to Front, r to Rear 
levels( mpg2$drv)[ levels( mpg2$drv) =="4"] <- "4wd" 
levels( mpg2$drv)[ levels( mpg2$drv) =="f"] <- "Front" 
levels( mpg2$drv)[ levels( mpg2$drv) =="r"] <- "Rear" 

# Plot the new data 
ggplot( mpg2, aes( x = displ, y = hwy)) + 
  geom_point() + facet_grid( drv ~ .)
```

## 4. Changing the Appearance of Facet Labels and Headers
```{r}
ggplot( cabbage_exp, aes( x = Cultivar, y = Weight)) + 
  geom_bar( stat ="identity") + 
  facet_grid(. ~ Date) + 
  theme( strip.text = element_text( face ="bold", size = rel( 1.5)), strip.background = element_rect( fill ="lightblue", colour ="black", size = 1))
```







