---
title: "liberty-mutual-fire-peril-EXPLONATORY"
output: html_document
---


Loading data sets (train, test, sample) ... 

```{r}
base.path = "C:/docs/ff/gitHub/fast-furious/dataset/liberty-mutual-group/"
base.path = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/liberty-mutual-fire-peril/"


train.fn = "train.csv"
test.fn = "test.csv"
sampleSub.fn = "sampleSubmission.csv"

library(data.table)
train = fread(paste(base.path,train.fn,sep="") , header = TRUE , sep=","  )

dim(train)  ## 452061    302
dim(train_no_NA)  # 452061    302
sum(train$target == 0) / dim(train)[1] ## 0.997372
sum(train$target == 0) ##450873 
sum(train$target != 0) ##1188

y = train$target
plot(density(y))

density(y)

density(y[y != 0])

min(y) #0
max(y) #25.92014 
mean(y) # 0.00723407
sd(y) # 0.2196884 

min(y[y != 0]) #0.005770778
plot(density(y[y != 0]))
mean(y[y != 0]) #2.752728
sd(y[y != 0]) # 3.288865
```

Performing data trasformation 

```{r}
## set NAs
train$var1 = ifelse(train$var1 == "Z" , NA , train$var1)
train$var2 = ifelse(train$var2 == "Z" , NA , train$var2)
train$var3 = ifelse(train$var3 == "Z" , NA , train$var3)
train$var4 = ifelse(train$var4 == "Z" , NA , train$var4)
train$var5 = ifelse(train$var5 == "Z" , NA , train$var5)
train$var6 = ifelse(train$var6 == "Z" , NA , train$var6)
train$var7 = ifelse(train$var7 == "Z" , NA , train$var7)
train$var8 = ifelse(train$var8 == "Z" , NA , train$var8)
train$var9 = ifelse(train$var9 == "Z" , NA , train$var9)

## set correct classes for regression 
train$var1 = as.numeric(train$var1)
train$var2 = as.factor(train$var2)
train$var3 = as.factor(train$var3)
train$var4 = as.factor(train$var4) ## TODO BETTER 
train$var5 = as.factor(train$var5)
train$var6 = as.factor(train$var6)
train$var7 = as.numeric(train$var7)
train$var8 = as.numeric(train$var8)
train$var9 = as.factor(train$var9)
train$dummy = as.factor(train$dummy)

## full linear model
lm.fit = lm( target ~ . , data = train )




```

