---
title: "Predictors Selection Interaction Terms"
author: "Gino Tesei"
date: "August 2, 2014"
output: html_document
---

Functions 
```{r}
library(quantreg)


WeightedGini <- function(solution, weights, submission){
  df = data.frame(solution = solution, weights = weights, submission = submission)
  df <- df[order(df$submission, decreasing = TRUE),]
  df$random = cumsum((df$weights/sum(df$weights)))
  totalPositive <- sum(df$solution * df$weights)
  df$cumPosFound <- cumsum(df$solution * df$weights)
  df$Lorentz <- df$cumPosFound / totalPositive
  n <- nrow(df)
  gini <- sum(df$Lorentz[-1]*df$random[-n]) - sum(df$Lorentz[-n]*df$random[-1])
  return(gini)
}

NormalizedWeightedGini <- function(solution, weights, submission) {
  WeightedGini(solution, weights, submission) / WeightedGini(solution, weights, solution)
}


encodeCategoricalFeature = function(ddata,i,facts.in=NULL) {
  fact_max = 0
  fact_min = 1 
  facts = NULL
  if (is.null(facts.in)) {
    facts = na.omit(unique(ddata[,i]))
    fact_max = length(facts)
  } else {
    fact_max = length(facts.in)
    facts = facts.in
  }
  
  mm = matrix(rep(0,dim(ddata)[1]),nrow=dim(ddata)[1],ncol=fact_max)
  col_name = colnames(ddata)[i]
  colnames(mm) = paste(paste(col_name,"_",sep=''),facts,sep='')
  for (j in fact_min:fact_max) {
    mm[,j] = ddata [,i] == facts[j]
  }  
  ddata = cbind(ddata,mm)
  #ddata = ddata[,-i]
}

bootstrap = function (traindata , labels , positive.ratio = 0.5) {
  pos.idx.set = which(labels == 1)
  neg.idx.set = which(labels == 0)
  
  traindata.pos.samples = floor(dim(traindata)[1] * positive.ratio)
  traindata.neg.samples = dim(traindata)[1] - traindata.pos.samples
  
  pos.idx = sample(pos.idx.set , traindata.pos.samples , T)
  neg.idx = sample(neg.idx.set , traindata.neg.samples , T)
  
  all.idx = c(pos.idx,neg.idx)
  
  traindata.boot = traindata[all.idx , ]
  traindata.boot
}

getPvalueTypeIError = function(x,y) {
  test = NA
  pvalue = NA
  
  ## type casting and understanding stat test 
  if (class(x) == "integer") x = as.numeric(x)
  if (class(y) == "integer") y = as.numeric(y)
  
  if ( class(x) == "factor" & class(y) == "numeric" ) {
    # C -> Q
    test = "ANOVA"
  } else if (class(x) == "factor" & class(y) == "factor" ) {
    # C -> C
    test = "CHI-SQUARE"
  } else if (class(x) == "numeric" & class(y) == "numeric" ) {
    test = "PEARSON"
  }  else {
    # Q -> C 
    # it performs anova test x ~ y 
    test = "ANOVA"
    tmp = x 
    x = y 
    y = tmp 
  }
  
  ## performing stat test and computing p-value
  if (test == "ANOVA") {                
    test.anova = aov(y~x)
    pvalue = summary(test.anova)[[1]][["Pr(>F)"]][1]
  } else if (test == "CHI-SQUARE") {    
    test.chisq = chisq.test(x = x , y = y)
    pvalue = test.chisq$p.value
  } else {                             
    ###  PEARSON
    test.corr = cor.test(x =  x , y =  y)
    pvalue = test.corr$p.value
  }
    
  pvalue
}

getPerfOnTestSet = function(x , y , k = 4) {
  reg.type = NA
  perf = NA
  
  if ( class(y) == "factor" & length(levels(y)) > 2 ) stop("TODO Multinomial support.")
  
  ## type casting and understanding stat test 
  if (class(x) == "integer") x = as.numeric(x)
  if (class(y) == "integer") y = as.numeric(y)
  
  if ( class(x) == "factor" & class(y) == "numeric" ) {
    # C -> Q
    reg.type = "LINEAR_REG"
  } else if (class(x) == "factor" & class(y) == "factor" ) {
    # C -> C
    reg.type = "LOGISTIC_REG"
  } else if (class(x) == "numeric" & class(y) == "numeric" ) {
    reg.type = "LINEAR_REG"
  }  else {
    # Q -> C 
    reg.type = "LOGISTIC_REG"
  }
  
  y = y[! is.na(x)]
  x = x[! is.na(x)]
  ## k-fold cross validation 
  folds = kfolds(k,length(x))
  cv=rep(x = -1 , k)
  
  if (reg.type == "LINEAR_REG") {
    for(j in 1:k) {  
      train.df = data.frame(y = y[folds != j] , x = x[folds != j])
      test.df = data.frame(x = x[folds == j])
      fit = lm(y ~ x , data=train.df)
      pred = predict(fit , test.df)
      cv[j]= mean(abs((y[folds == j] - pred)))
    }
  } else { #LOGISTIC_REG
    for(j in 1:k) {  
      train.df = data.frame(y = y[folds != j] , x = x[folds != j])
      test.df = data.frame(x = x[folds == j])
      fit = glm(y ~ x , data=train.df , family=binomial)
      pred.probs = predict(fit , test.df , type = "response")
      label0 = rownames(contrasts(y))[1]
      label1 = rownames(contrasts(y))[2]
      pred = ifelse(pred.probs > 0.5 , label1 , label0)
      cv[j]= mean( y[folds == j] == pred  )
    }
  }
  
  perf=mean(cv)
  perf
}

getLinerRegPerfXval = function(form, train, k=4) {
  
  #k = 4 
  #form = "target ~ var11 + var12 + var13 + var14 + var15 + var16 + var17 "
  
  folds = kfolds(k,dim(train)[1])
  cv=rep(x = -1 , k)
  
  for(j in 1:k) {  
      traindata = train[folds != j,]
      xvaldata = train[folds == j,]
      fit = lm(as.formula(form) , data=traindata)
      #fit = rq(as.formula(form) , data=traindata , tau = 0.1 )
      pred = predict(fit , xvaldata)
      pred = ifelse(is.na(pred) , 0 , pred)    ## TODO BETTER 
      #cv[j]= mean(abs((xvaldata$target - pred)))
      cv[j] = NormalizedWeightedGini (xvaldata$target, xvaldata$var11, pred)
    }
  
  perf=mean(cv)
  perf
}

getPvalueInteractionTerms = function(response,features,pvalueFeatures,pvalue.threshold = 0.05) {
  
  n = dim(features)[2] * (dim(features)[2] - 1) / 2 
  
  label.formula = rep(NA, n)
  pValue <- rep(NA, n)
  is.na <- rep(NA, n)
  perf.xval <- rep(NA, n)
  
  p = 1 
  for (i in 1:(dim(features)[2]) ) {
    if ( class(features[,i]) == "factor" ) next 
    if ( ! is.na(pvalueFeatures$pValue[pvalueFeatures$label == colnames(features[i])]) & pvalueFeatures$pValue[pvalueFeatures$label == colnames(features[i])] > pvalue.threshold) next 
    
    for (j in (i+1):(dim(features)[2]) ) {
       if ( class(features[,j]) == "factor" ) next 
       if ( ! is.na(pvalueFeatures$pValue[pvalueFeatures$label == colnames(features[j])]) & pvalueFeatures$pValue[pvalueFeatures$label == colnames(features[j])] > pvalue.threshold) next
       
       label.formula[p] = paste0(paste0( colnames(features[i]) , ":" ) , colnames(features[j]) )
       pValue[p] <- getPvalueTypeIError(x = (features[,i]*features[,j]), y = response)
       perf.xval[p] = getPerfOnTestSet(x = (features[,i]*features[,j]) , y = response)
       is.na[p] = sum(is.na(  features[,i]*features[,j]  )) / length(features[,i]) 
       
       p = p + 1
    }
  }
  
  is.significant = ifelse(pValue < 0.05,T,F)
  
  ## trim 
  idx = which(! is.na(label.formula) )
  label.formula = label.formula[idx]
  pValue <- pValue[idx]
  is.na <- is.na[idx]
  perf.xval <- perf.xval[idx]
  is.significant = is.significant[idx]
  
  ## return 
  data.frame(label = label.formula, pValue , is.significant , is.na , perf.xval)
}

getPvalueFeatures = function(response,features , p = 1) {
  
  label.formula = rep(NA, dim(features)[2])
  pValue <- rep(NA, dim(features)[2])
  is.na <- rep(NA, dim(features)[2])
  perf.xval <- rep(NA, dim(features)[2])
  
  for (i in 1:(dim(features)[2])) {
    if ( p == 1) {
      label.formula[i] = colnames(features[i])
      pValue[i] <- getPvalueTypeIError(x = features[,i], y = response)
      perf.xval[i] = getPerfOnTestSet(x = features[,i], y = response)
    } else {
      ## label 
      if (p == 2) label.formula[i] = paste0(paste0("I(",colnames(features[i])),"^2)")
      if (p == 3) label.formula[i] = paste0(paste0("I(",colnames(features[i])),"^3)")
      if (p == 4) label.formula[i] = paste0(paste0("I(",colnames(features[i])),"^4)")
      if (p == 5) label.formula[i] = paste0(paste0("I(",colnames(features[i])),"^5)")
      if (p >  5) stop("p > 5 not supported.")
      
      ## pvalue , perf.xval
      if (class(features[,i]) == "factor") {
        pValue[i] = NA
        perf.xval[i] = NA
      } else {
        x.poly = features[,i]^p
        pValue[i] = getPvalueTypeIError(x = x.poly, y = response)
        perf.xval[i] = getPerfOnTestSet(x = x.poly, y = response)
      }
    }
    
    is.na[i] = sum(is.na(features[,i])) / length(features[,i]) 
  }
    
  is.significant = ifelse(pValue < 0.05,T,F)
  data.frame(label = label.formula, pValue , is.significant , is.na , perf.xval)
}

kfolds = function(k,data.length) {
  k = min(k,data.length)
  folds = rep(NA,data.length)
  labels = 1:data.length
  st = floor(data.length/k)
  al_labels = NULL
  for (s in 1:k) {
    x = NULL
    if (is.null(al_labels))
      x = sample(labels,st)
    else
      x = sample(labels[-al_labels],st)
    
    folds[x] = s
    if (is.null(al_labels))
      al_labels = x
    else
      al_labels = c(al_labels,x)
    }
  ss = 1
  for (s in 1:length(folds)){
    if (is.na(folds[s])) {
      folds[s] = ss
      ss = ss + 1
      } 
    }
  folds
}

```

Loading data sets (train, test, sample) ... 

```{r , warning=FALSE}
#base.path = "C:/docs/ff/gitHub/fast-furious/dataset/liberty-mutual-fire-peril/"
base.path = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/liberty-mutual-fire-peril/"

train.fn = "train.csv"
test.fn = "test.csv"
sampleSub.fn = "sampleSubmission.csv"

predictors.reg.linear.fn  = "predictors_reg_linear.csv"
predictors.reg.linear2.fn  = "predictors_reg_linear_2.csv"
predictors.reg.linear3.fn  = "predictors_reg_linear_3.csv"
predictors.reg.linear4.fn  = "predictors_reg_linear_4.csv"
predictors.reg.linear5.fn  = "predictors_reg_linear_5.csv"

predictors.class.linear.fn  = "predictors_class_linear.csv"
predictors.class.linear2.fn  = "predictors_class_linear_2.csv"
predictors.class.linear3.fn  = "predictors_class_linear_3.csv"
predictors.class.linear4.fn  = "predictors_class_linear_4.csv"
predictors.class.linear5.fn  = "predictors_class_linear_5.csv"

predictors.reg.interaction.fn  = "predictors_reg_interaction_terms_.csv"
predictors.class.interaction.fn  = "predictors_class_interaction_terms_.csv"

library(data.table)
train.tab = fread(paste(base.path,train.fn,sep="") , header = TRUE , sep=","  )

predictors.reg.linear = read.csv(paste(base.path,predictors.reg.linear.fn,sep="") , sep=","  )
predictors.reg.linear2 = read.csv(paste(base.path,predictors.reg.linear2.fn,sep="") , sep=","  )
predictors.reg.linear3 = read.csv(paste(base.path,predictors.reg.linear3.fn,sep="") , sep=","  )
predictors.reg.linear4= read.csv(paste(base.path,predictors.reg.linear4.fn,sep="") , sep=","  )
predictors.reg.linear5 = read.csv(paste(base.path,predictors.reg.linear5.fn,sep="") , sep=","  )

predictors.class.linear = read.csv(paste(base.path,predictors.class.linear.fn,sep="") ,  sep=","  )
predictors.class.linear2 = read.csv(paste(base.path,predictors.class.linear2.fn,sep="") ,  sep=","  )
predictors.class.linear3 = read.csv(paste(base.path,predictors.class.linear3.fn,sep="") ,  sep=","  )
predictors.class.linear4 = read.csv(paste(base.path,predictors.class.linear4.fn,sep="") ,  sep=","  )
predictors.class.linear5 = read.csv(paste(base.path,predictors.class.linear5.fn,sep="") ,  sep=","  )

predictors.reg.interaction =  read.csv(paste(base.path,predictors.reg.interaction.fn,sep="") ,  sep=","  )
#predictors.class.interaction = read.csv(paste(base.path,predictors.class.interaction.fn,sep="") ,  sep=","  )
```

Performing data trasformation 

```{r}
train = as.data.frame.matrix(train.tab) 
## set NAs
train$var1 = ifelse(train$var1 == "Z" , NA , train$var1)
train$var2 = ifelse(train$var2 == "Z" , NA , train$var2)
train$var3 = ifelse(train$var3 == "Z" , NA , train$var3)
train$var4 = ifelse(train$var4 == "Z" , NA , train$var4)
train$var5 = ifelse(train$var5 == "Z" , NA , train$var5)
train$var6 = ifelse(train$var6 == "Z" , NA , train$var6)
train$var7 = ifelse(train$var7 == "Z" , NA , train$var7)
train$var8 = ifelse(train$var8 == "Z" , NA , train$var8)
train$var9 = ifelse(train$var9 == "Z" , NA , train$var9)

## set correct classes for regression 
train$var1 = as.numeric(train$var1)
train$var2 = as.factor(train$var2)
train$var3 = as.factor(train$var3)

## TODO BETTER: perdi l'informazione sul secondo livello  
#train$var4_4 = factor(train$var4 , ordered = T)
train$var4_4 = factor(train$var4 )
#train$var4 = factor( ifelse(is.na(train$var4), NA , substring(train$var4 , 1 ,1) ) , ordered = T)
train$var4 = factor( ifelse(is.na(train$var4), NA , substring(train$var4 , 1 ,1) ) )

train$var5 = as.factor(train$var5)
train$var6 = as.factor(train$var6)
train$var7 = as.numeric(train$var7)
train$var8 = as.numeric(train$var8)
train$var9 = as.factor(train$var9)
train$dummy = as.factor(train$dummy)

train$target_0 = factor(ifelse(train$target == 0,0,1))

## all0s model 
all0.mae = mean(abs(train$target))
all0.acc = mean(train$target_0 == 0)
all0.mae
all0.acc

### merge reg
p.thresold = 0.05 
na.thresold = 0.5 

# reg.merge = predictors.reg.linear
# reg.merge = rbind(reg.merge , predictors.reg.linear2)
# reg.merge = rbind(reg.merge , predictors.reg.linear3)
# reg.merge = rbind(reg.merge , predictors.reg.linear4)
# reg.merge = rbind(reg.merge , predictors.reg.linear5)
# reg.merge = rbind(reg.merge , predictors.reg.interaction)

reg.merge = predictors.class.linear
reg.merge = rbind(reg.merge , predictors.class.linear2)
reg.merge = rbind(reg.merge , predictors.class.linear3)
reg.merge = rbind(reg.merge , predictors.class.linear4)
reg.merge = rbind(reg.merge , predictors.class.linear5)
reg.merge = rbind(reg.merge , predictors.class.interaction)

reg.merge.ord.pvalue = reg.merge[order(reg.merge$pValue) , ]
head(reg.merge.ord.pvalue)

reg.merge.ord.perf.xval = reg.merge[order(reg.merge$perf.xval) , ]
head(reg.merge.ord.perf.xval)

#### trying pvalue order with no constraints 
formulas = rep(NA,dim(reg.merge.ord.pvalue)[1])
perf = rep(NA,dim(reg.merge.ord.pvalue)[1])

form = "target ~ "
p = 1 
perf.xval.best = NULL

for (i in 1:dim(reg.merge.ord.pvalue)[1]) {
  t = reg.merge.ord.pvalue[i,]
  
  form.prev = form 
  if (i == 1) {
    form = paste0(form,t$label)
  } else {
    form = paste0(paste0(form," + "),t$label)
  }
  
  cat("model:",form,"  (adding:", toString(t$label)  , " - na perc. = " , t$is.na, ")\n")
  perf.xval = getLinerRegPerfXval(form = form, train = train)
  cat("xval.perf:",perf.xval,"\n")
  
  if (is.null(perf.xval.best)) {
    perf.xval.best = perf.xval
  } else {
    if (perf.xval > perf.xval.best) {
      perf.xval.best = perf.xval
    } else {
      formulas[p] = form.prev
      perf[p] = perf.xval.best
      
      form = paste0("target ~ ", t$label )
      cat("model:",form,"  (adding:", toString(t$label)  , " - na perc. = " , t$is.na, ")\n")
      perf.xval = getLinerRegPerfXval(form = form, train = train)
      perf.xval.best = perf.xval
      cat("xval.perf:",perf.xval,"\n")
      
      p = p + 1
    }
  } 
} 

idx = which(!is.na(formulas))
formulas = formulas[idx]
perf = perf[idx]

results = data.frame(fomula = formulas , perf = perf)
results[order(results$perf , decreasing = T) , ]

results.fn = paste0(base.path,"results_class_linear.csv")
write.csv(results,quote=F,row.names=F,file=results.fn)
```
