Acquire Valued Shoppers Challenge  -- no encoding  
========================================================

Metrics For Kaggle Competions
```{r}
#### Alec Stephenson ####
#### Metrics For Kaggle Competions ####
#### No Copyright Use At Own Risk ####
#### Code based on several posting on forums ####
#### by a number of different individuals. ####

#### The AUC Metric ####

auc <- function (pred, act) 
{
  if(!is.numeric(pred)) stop("'pred' must be numeric")
  if(!is.numeric(act)) stop("'act' must be numeric")
  if(!all(act %in% c(0,1))) stop("'act' must be binary")  
  if(length(pred) != length(act)) stop("'pred' and 'act' must have the same length")
  
  n0 <- sum(1-act); n1 <- sum(act)
  r <- rank(pred)[act==1]
  (sum(r) - n1 * (n1 + 1)/2)/(n0 * n1)
}

#### The Gini and Normalized Gini Metrics ####

gini <- function(pred, act, norm = FALSE) 
{
  if(!is.numeric(pred)) stop("'pred' must be numeric")
  if(!is.numeric(act)) stop("'act' must be numeric")
  if(!all(act %in% c(0,1))) stop("'act' must be binary")  
  if(length(pred) != length(act)) stop("'pred' and 'act' must have the same length")
  
  nn <- length(act); n1 <- sum(act)
  loss <- act[order(pred, decreasing=TRUE)]
  ginival <- (sum((nn:1) * loss/n1) - (nn + 1)/2)/nn
  if(norm) ginival <- 2*ginival/(1-n1/nn)
  ginival
}

#### Capped Binomial Deviance ####

cbinom <- function(pred, act, cap = c(0.01,0.99)) 
{
  if(!is.numeric(pred)) stop("'pred' must be numeric")
  if(!is.numeric(act)) stop("'act' must be numeric")
  if(!all(act %in% c(0,1))) stop("'act' must be binary")  
  if(length(pred) != length(act)) stop("'pred' and 'act' must have the same length")
  
  pred <- pmax.int(pmin.int(pred, cap[2]), cap[1])
  -sum(act*log10(pred) + (1-act)*log10(1-pred))/length(pred)
}

#### Root Mean Squared (Percentage) Error ####

rmse <- function(pred, act, norm = FALSE) 
{
  if(!is.numeric(pred)) stop("'pred' must be numeric")
  if(!is.numeric(act)) stop("'act' must be numeric") 
  if(length(pred) != length(act)) stop("'pred' and 'act' must have the same length")
  
  errs <- pred - act
  if(norm) errs <- errs/act
  sqrt(sum(errs^2)/length(pred))
}

#### Mean Absolute (Percentage) Error ####

mae <- function(pred, act, norm = FALSE) 
{
  if(!is.numeric(pred)) stop("'pred' must be numeric")
  if(!is.numeric(act)) stop("'act' must be numeric") 
  if(length(pred) != length(act)) stop("'pred' and 'act' must have the same length")
  
  errs <- pred - act
  if(norm) errs <- errs/act
  sum(abs(errs))/length(pred)
}

nomalize = function(ddata,i,min.in=NULL,max.in=NULL) {
  n_col = NULL
  if( is.null(min.in) | is.null(max.in) )  { 
    n_col = (ddata[,i] - min(ddata[,i])) / (  max(ddata[,i])  - min (ddata[,i]) )
  } else {
    n_col = (ddata[,i] - min.in) / (  max.in  - min.in )
  }
  
  col_name = colnames(ddata)[i]
  n_col_df = data.frame(  n_col   )
  colnames(n_col_df) = paste(col_name,"_norm",sep="")
  ddata = cbind(ddata,n_col_df)
  ddata = ddata[,-i]
}

jitter.matrix = function(mat) {
  for (i in 1:length(colnames(mat))) {
    mat[, i] = jitter(mat[,i])
  }
  mat
}

```

```{r}
### load files 
base.path = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/acquire-valued-shoppers-challenge/"
#base.path = "C:/docs/ff/gitHub/fast-furious/dataset/acquire-valued-shoppers-challenge/"

offers.fn = paste(base.path,"offers",sep="")
# testHistory.fn = paste(base.path,"testHistory",sep="")
# trainHistory.fn = paste(base.path,"trainHistory",sep="")
testHistory.fn = paste(base.path,"test_history_ext.csv",sep="")
trainHistory.fn = paste(base.path,"train_history_ext.csv",sep="")
submission.fn = paste(base.path,"sampleSubmission",sep="")

offers.csv = read.csv(offers.fn)
testHistory.csv = read.csv(testHistory.fn)
trainHistory.csv = read.csv(trainHistory.fn)
submission.csv = read.csv(submission.fn)

ptm <- proc.time()
```

building model ... 

```{r}
traindata = merge(offers.csv,trainHistory.csv,by.x=c("offer"),by.y=c("OFFER"),all.x=F,all.y=F)
traindata = traindata[,-c(1,12)] ## offer , offerdate
traindata$repeater = ifelse(traindata$repeater == "t" , 1, 0) 

testdata = merge(offers.csv,testHistory.csv,by.x=c("offer"),by.y=c("OFFER"),all.x=F,all.y=F)
testdata = testdata[,-c(1,10)] ## offer , offerdate

ids = testHistory.csv$ID

### Xtest 
Xtest = testdata[,c(6,7,8,1,2,3,4,5,9,10,11)]

### Xtrain 
Xtrain = traindata[,c(6,7,8,1,2,3,4,5,11,12,13)]

Xtrain = Xtrain[,-c(1,2,5)] 
Xtest = Xtest[,-c(1,2,5)]

Xtrain = jitter.matrix(Xtrain)
Xtest = jitter.matrix(Xtest)

### ytrain 
ytrain = traindata$repeater
```

```{r}
########## XVAL 
# d_train = floor(dim(Xtrain)[1] * 0.7)
# ytrain.train = ytrain[1:d_train]
# ytrain.xval = ytrain[(d_train+1):dim(Xtrain)[1]]
# Xtrain.train = Xtrain[1:d_train , ]
# Xtrain.xval = Xtrain[(d_train+1):dim(Xtrain)[1],]
# 
# glm.fit = glm( ytrain.train ~  . , data = Xtrain.train , family="binomial" )
# glm.fit$xlevels[['company']] = union (glm.fit$xlevels[['company']] , levels(Xtrain.xval$company) ) 
# glm.fit$xlevels[['category']] = union (glm.fit$xlevels[['category']] , levels(Xtrain.xval$category) )
# glm.fit$xlevels[['brand']] = union (glm.fit$xlevels[['brand']] , levels(Xtrain.xval$brand) )
# glm.fit$xlevels[['CHAIN']] = union (glm.fit$xlevels[['CHAIN']] , levels(Xtrain.xval$CHAIN) )
# glm.pred.xval = predict(glm.fit , Xtrain.xval , type="response") 
# auc.train = auc(glm.pred.xval, ytrain.xval) 
# print(auc.train)
# ### [1] 0.5584764 
# 
# glm.fit = glm( ytrain ~  . , data = Xtrain , family="binomial" )
# glm.pred.train = predict(glm.fit ,  type="response") 
# glm.pred.test = predict(glm.fit , data = Xtest , type="response") [1:151484]
# glm.pred.test.sub = ifelse(glm.pred.test > 0.5 , 1, 0)
# sub = data.frame(id = ids , repeatProbability = glm.pred.test.sub)
# sub.fn = paste(base.path,"sub.glm.zat",sep="")
# write.csv(sub,quote=F,row.names=F,file=sub.fn)
# ### Your submission scored 0.51184, which is not an improvement of your best score. Keep trying!

library(quantreg)
rq.tau <- 0.5 # you can use other tau like 0.6
rq.model <- rq(ytrain~., data=Xtrain, tau=rq.tau)
summary(rq.model)
rq.pred <- predict(rq.model, new.data=Xtest)
sub = data.frame(id = ids , repeatProbability = rq.pred)
sub.fn = paste(base.path,"sub.rq.zat",sep="")
write.csv(sub,quote=F,row.names=F,file=sub.fn)

```
