Acquire Valued Shoppers Challenge 
========================================================

```{r}
encodeCategoricalFeature = function(ddata,i,facts.in=NULL) {
  
  fact_max = 0
  fact_min = 1 
  facts = NULL
  if (is.null(facts.in)) {
    fact_max = length(unique(ddata[,i]))
    facts = unique(ddata[,i])
  } else {
    fact_max = length(facts.in)
    facts = facts.in
  }
  
  mm = matrix(rep(0,dim(ddata)[1]),nrow=dim(ddata)[1],ncol=fact_max)
  col_name = colnames(ddata)[i]
  colnames(mm) = paste(paste(col_name,"_",sep=''),facts,sep='')
  for (j in fact_min:fact_max) {
    mm[,j] = ddata [,i] == facts[j]
  }  
  ddata = cbind(ddata,mm)
  ddata = ddata[,-i]
}

nomalize = function(ddata,i,min.in=NULL,max.in=NULL) {
  n_col = NULL
  if( is.null(min.in) | is.null(max.in) )  { 
    n_col = (ddata[,i] - min(ddata[,i])) / (  max(ddata[,i])  - min (ddata[,i]) )
  } else {
    n_col = (ddata[,i] - min.in) / (  max.in  - min.in )
  }
  
  col_name = colnames(ddata)[i]
  n_col_df = data.frame(  n_col   )
  colnames(n_col_df) = paste(col_name,"_norm",sep="")
  ddata = cbind(ddata,n_col_df)
  ddata = ddata[,-i]
}
```

```{r}
### load files 
#base.path = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/acquire-valued-shoppers-challenge/"
base.path = "C:/docs/ff/gitHub/fast-furious/dataset/acquire-valued-shoppers-challenge/"

offers.fn = paste(base.path,"offers",sep="")
testHistory.fn = paste(base.path,"testHistory",sep="")
trainHistory.fn = paste(base.path,"trainHistory",sep="")
submission.fn = paste(base.path,"sampleSubmission",sep="")

offers.csv = read.csv(offers.fn)
testHistory.csv = read.csv(testHistory.fn)
trainHistory.csv = read.csv(trainHistory.fn)
submission.csv = read.csv(submission.fn)

ptm <- proc.time()
```

building model ... 

```{r}

traindata = merge(offers.csv,trainHistory.csv,by.x=c("offer"),by.y=c("offer"),all.x=F,all.y=F)
traindata = traindata[,-c(1,12)] ## offer , offerdate
traindata$repeater = ifelse(traindata$repeater == "t" , 1, 0) 

testdata = merge(offers.csv,testHistory.csv,by.x=c("offer"),by.y=c("offer"),all.x=F,all.y=F)
testdata = testdata[,-c(1,10)] ## offer , offerdate

### Xtest 
Xtest = testdata[,c(6,7,8,1,2,3,4,5)]

### Xtrain 
Xtrain = traindata[,c(6,7,8,1,2,3,4,5)]

facts = unique(c(Xtrain$chain,Xtest$chain))
Xtrain = encodeCategoricalFeature(Xtrain,2,facts.in=facts) ## chain 
Xtest = encodeCategoricalFeature(Xtest,2,facts.in=facts) ## chain 

facts = unique(c(Xtrain$market,Xtest$market))
Xtrain = encodeCategoricalFeature(Xtrain,2,facts.in=facts) ## market
Xtest = encodeCategoricalFeature(Xtest,2,facts.in=facts) ## market

facts = unique(c(Xtrain$category,Xtest$category))
Xtrain = encodeCategoricalFeature(Xtrain,2,facts.in=facts) ## category
Xtest = encodeCategoricalFeature(Xtest,2,facts.in=facts) ## category

facts = unique(c(Xtrain$company,Xtest$company))
Xtrain = encodeCategoricalFeature(Xtrain,3,facts.in=facts) ## company
Xtest = encodeCategoricalFeature(Xtest,3,facts.in=facts) ## company

facts = unique(c(Xtrain$brand,Xtest$brand))
Xtrain = encodeCategoricalFeature(Xtrain,4,facts.in=facts) ## brand
Xtest = encodeCategoricalFeature(Xtest,4,facts.in=facts) ## brand

Xtrain = Xtrain[,-2] ## quantity ha il solo valore 1
Xtest = Xtest[,-2] ## quantity ha il solo valore 1

mi = min(c(Xtrain$offervalue,Xtest$offervalue))
ma = max(c(Xtrain$offervalue,Xtest$offervalue))
Xtrain = nomalize(Xtrain,2,min.in=mi,max.in=ma)
Xtest = nomalize(Xtest,2,min.in=mi,max.in=ma)

Xtrain = Xtrain[,-1] ## ids sono diversi tra loro 
Xtest = Xtest[,-1] ## ids sono diversi tra loro 


### ytrain 
ytrain = traindata$repeater


#### storing on fs ...
Xtrain.fn = paste(base.path,"Xtrain.zat",sep="")
write.csv(Xtrain,quote=F,row.names=F,file=Xtrain.fn)

Xtest.fn = paste(base.path,"Xtest.zat",sep="")
write.csv(Xtest,quote=F,row.names=F,file=Xtest.fn)

ytrain.fn = paste(base.path,"ytrain.zat",sep="")
write.csv(ytrain,quote=F,row.names=F,file=ytrain.fn)

# ids = testHistory.csv$id
# id.fn = paste(base.path,"id.zat",sep="")
# write.csv(ids,quote=F,row.names=F,file=id.fn)
```