---
title: "AxaExp1"
output: html_document
---

```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(caret)
library(Hmisc)
library(data.table)
library(verification)
library(pROC)
library(kernlab)
library(subselect)
library(plyr)
library(binhf)

getTrips = function (drv = 0) {
  ret = ""
  
  base.path1 = "C:/docs/ff/gitHub/fast-furious/dataset/axa-driver-telematics-analysis/drivers/"
  base.path2 = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/axa-driver-telematics-analysis/drivers/"
  
  base.path1 = paste( base.path1, as.character(drv) , sep = "") 
  base.path2 = paste( base.path2, as.character(drv) , "/" , sep = "") 
  
  if (file.exists(base.path1))  {
    
    ret = order (as.numeric (lapply(list.files(base.path1), function(x) as.numeric ( substr(x, 1, nchar(x) - 4)) )) , decreasing = F)
    
  } else if (file.exists(base.path2)) {
    
    ret = order (as.numeric (lapply(list.files(base.path2), function(x) as.numeric ( substr(x, 1, nchar(x) - 4)) )) , decreasing = F)
  } else {
    ret = NA
  }
  
  ret
}


getDrivers = function () {
  ret = ""
  
  base.path1 = "C:/docs/ff/gitHub/fast-furious/dataset/axa-driver-telematics-analysis/drivers"
  base.path2 = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/axa-driver-telematics-analysis/drivers/"
  
  if (file.exists(base.path1))  {
    
    ret = order (as.numeric (lapply(list.files(base.path1), function(x) as.numeric (x)) , decreasing = F) )
    
  } else if (file.exists(base.path2)) {
    
    ret = order (as.numeric (lapply(list.files(base.path2), function(x) as.numeric (x)) , decreasing = F) )
  } else {
    ret = NA
  }
  
  ret
}


getTripPath = function (driver = 0 , trip = 0) {
  ret = ""
  
  base.path1 = "C:/docs/ff/gitHub/fast-furious/dataset/axa-driver-telematics-analysis/drivers/"
  base.path2 = "/Users/gino/kaggle/fast-furious/gitHub/fast-furious/dataset/axa-driver-telematics-analysis/drivers/"
  
  base.path1 = paste( base.path1, as.character(driver) , "/" , as.character(trip) , ".csv" , sep = "") 
  base.path2 = paste( base.path2, as.character(driver) , "/" , as.character(trip) , ".csv" , sep = "") 
  
  if (file.exists(base.path1))  {
    ret = base.path1
  } else if (file.exists(base.path2)) {
    ret = base.path2
  } else {
    ret = NA
  }
  
  ret
} 

findMainFrequencyComponent  = function (fsamp , Time , sign ,doPlot=F) { 
  FFT <- fft(sign)
  magn <- Mod(FFT) # sqrt(Re(test)*Re(test)+Im(test)*Im(test))
  magn.1 <- magn[1:(length(magn)/2)]
  phase <- Arg(FFT) # atan(Im(test)/Re(test))
  x.axis <- 1:length(magn.1)/Time
  mi = which(magn.1 == max(magn.1))
  ret = x.axis[mi]
  
  if (doPlot) {
    plot(x=x.axis,y=magn.1,type="l",xlab="Hz",ylab="u.m. of observed phenomenon")
  }
  
  ret
}

PSD  = function (fs,Time,sign,doPlot=F) { 
  
  N = length(Time)
  fNyq = fs / 2 
  Nf <- N/2 
  
  
  FFT <- fft(sign)
  magn <- Mod(FFT) # sqrt(Re(test)*Re(test)+Im(test)*Im(test))
  magn.1 <- magn[1:(length(magn)/2)]
  phase <- Arg(FFT) # atan(Im(test)/Re(test))
  x.axis <- 1:length(magn.1)/Time
  
  Sa <- Mod(FFT) # Amplitude spectrum
  Sp <- Arg(FFT) # Phase spectrum
  XC <- Conj(FFT)
  Se <- Sa^2
  all.equal(Se <- Sa^2, Se_2 <- Mod(XC * FFT), Se_2R <- Mod(FFT * XC))
  
  pp = sum(Se[2:(Nf + 1)]) * 2/N
  
  if (doPlot) {
    plot(x=x.axis,y=magn.1,type="l",xlab="Hz",ylab="u.m. of observed phenomenon")
  }
  
  pp
 
}

```



```{r}

######################### settings ans constants 
debug = T

######################### main loop 

DRIVERS = c(1,23)
TRIPS = c(1,26)

ALL_DRIVERS = getDrivers() 
if (exists("DRIVERS")) 
  ALL_DRIVERS = intersect(ALL_DRIVERS,DRIVERS)
  
cat("|--------------------------------->>> found ",length(ALL_DRIVERS)," drivers ... \n")

for ( drv in ALL_DRIVERS  ) {
  
    trips = getTrips(drv) 
    if (exists("TRIPS")) 
      trips = intersect(trips,TRIPS)
    
    cat("|---------------->>> found <<",length(trips),">>  trips for driver <<",drv,">> ..\n")
    for (trip in trips) {
        
        ############ TRIP PROCESSING - begin 
        cat("|---------------->>> processing driver: <<",drv,">>  <<",trip,">> ..\n")
        
        #### load data 
        trdata = as.data.frame(fread(getTripPath(drv,trip)))
        if (debug) print(head(trdata))
        
        #### extract 1-tier features  
        
        ## rho 
        trdata$rho = apply(trdata,1,function(x) {
              sqrt(x[1]^2 + x[2]^2)
            })
        
        ## alpha 
        trdata$alpha = apply(trdata,1,function(x) {
          ret = 0 
          if (x[1] == 0) ret = 0
          else ret = atan(x[2]/x[1])
          ret
        })
        
        ## vx 
        trdata$vx =  trdata$x - shift(trdata$x,1)
        trdata$vx[1] = 0
        
        ## vy
        trdata$vy =  trdata$y - shift(trdata$y,1)
        trdata$vy[1] = 0
        
        ## V 
        trdata$V =  apply(trdata,1,function(x) {
          sqrt(x[5]^2 + x[6]^2)
        })
        
        ## ax 
        trdata$ax =  trdata$vx - shift(trdata$vx,1)
        trdata$ax[1] = 0
        
        ## ay
        trdata$ay =  trdata$vy - shift(trdata$vy,1)
        trdata$ay[1] = 0
        
        ## A 
        trdata$A =  apply(trdata,1,function(x) {
          sqrt(x[8]^2 + x[9]^2)
        })
        
        #### plot   
        
        if (debug) print(head(trdata))
        
        mlab = paste("Driver=" , drv , " - Trip=",trip,sep = "")
        
        plot( seq(1:dim(trdata)[1]) , trdata$x,  xlab="(secs)", ylab="x", type="l" , main = mlab)
        plot( seq(1:dim(trdata)[1]) , trdata$y,  xlab="(secs)", ylab="y", type="l" , main = mlab)
        
        plot( seq(1:dim(trdata)[1]) , trdata$rho,  xlab="(secs)", ylab="rho", type="l" , main = mlab)
        plot( seq(1:dim(trdata)[1]) , trdata$alpha,  xlab="(secs)", ylab="alpha", type="l" , main = mlab)
        
        plot( seq(1:dim(trdata)[1]) , trdata$vx,  xlab="(secs)", ylab="Vx", type="l" , main = mlab)
        plot( seq(1:dim(trdata)[1]) , trdata$vy,  xlab="(secs)", ylab="Vy", type="l" , main = mlab)
        plot( seq(1:dim(trdata)[1]) , trdata$V,  xlab="(secs)", ylab="V", type="l" , main = mlab)
        fmc = findMainFrequencyComponent(fsamp=1,Time=dim(trdata)[1],sign=trdata$V,doPlot=T) 
        cat("freq main comp = ",fmc,"\n")
        psd = PSD(1,dim(trdata)[1],trdata$V,doPlot=F)
        cat(" psd = ",psd,"\n")
        
        plot( seq(1:dim(trdata)[1]) , trdata$ax,  xlab="(secs)", ylab="Ax", type="l" , main = mlab)
        plot( seq(1:dim(trdata)[1]) , trdata$ay,  xlab="(secs)", ylab="Ay", type="l" , main = mlab)
        plot( seq(1:dim(trdata)[1]) , trdata$A,  xlab="(secs)", ylab="A", type="l" , main = mlab)
        findMainFrequencyComponent(fsamp=1,Time=dim(trdata)[1],sign=trdata$A,doPlot=T)
        cat("freq main comp = ",fmc,"\n")
        psd = PSD(1,dim(trdata)[1],trdata$A,doPlot=F)
        cat(" psd = ",psd,"\n")
        
        
        ############ TRIP PROCESSING - end  
      }
} 


```
